#!/bin/sh

EWW="/bin/eww -c $(pwd)"
EWW2="/bin/eww -c $(pwd)/multiple-windows"
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

run_eww() {
	${EWW} open bar
	${EWW2} open-many bar2 \
		bar3 \
		bar4 

        
}

run_eww
