#!/bin/sh


WIFI_ICON="󰤨"
ETH_ICON="󰈀"


wifi_iface=$(awk 'NR>2 {print $1}' /proc/net/wireless | sed 's/://')
if [ -n "$wifi_iface" ]; then
    ssid=$(iwconfig "$wifi_iface" 2>/dev/null | awk -F '"' '/ESSID/ {print $2}')
    if [ -n "$ssid" ] && [ "$ssid" != "off/any" ]; then
        echo "${WIFI_ICON} ${ssid}"
        exit
    fi
fi

for iface in /sys/class/net/*; do
    iface=$(basename "$iface")
    [ "$iface" = "lo" ] && continue
    [ -d "/sys/class/net/$iface/wireless" ] && continue

    if [ "$(cat /sys/class/net/$iface/operstate 2>/dev/null)" = "up" ]; then
        echo "${ETH_ICON}  ${iface}"
        exit
    fi
done

echo "No Connection"
