#!/bin/sh

volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}')
percent=$(printf "%.0f" "$(echo "$volume * 100" | bc)")

if [ "$percent" -eq 0 ]; then
    printf "  %s%%\n" "$percent"
else
    printf "  %s%%\n" "$percent"
fi
