#!/bin/sh
  
# Get current value of workspace variable  
current=$(/bin/eww get workspace -c ../.)  
  
# Toggle the value  
if [ "$current" = "true" ]; then  
    eww update workspace=false  
else  
    eww update workspace=true  
fi