--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/zyxtyz/.config/zyxtyz/wallpapers/rain_outside.jpg"

-- Special
background="#0d151f"
foreground="#c2c4c7"
cursor="#c2c4c7"

-- Colors
color0="#0d151f"
color1="#445293"
color2="#4B5A9C"
color3="#54788F"
color4="#5D839B"
color5="#61869D"
color6="#678CA2"
color7="#c2c4c7"
color8="#5c6571"
color9="#445293"
color10="#4B5A9C"
color11="#54788F"
color12="#5D839B"
color13="#61869D"
color14="#678CA2"
color15="#c2c4c7"
