# Shell variables
# Generated by 'wal'
wallpaper="/home/zyxtyz/.config/zyxtyz/wallpapers/rain_outside.jpg"

# Special
background='#0d151f'
foreground='#c2c4c7'
cursor='#c2c4c7'

# Colors
color0='#0d151f'
color1='#445293'
color2='#4B5A9C'
color3='#54788F'
color4='#5D839B'
color5='#61869D'
color6='#678CA2'
color7='#c2c4c7'
color8='#5c6571'
color9='#445293'
color10='#4B5A9C'
color11='#54788F'
color12='#5D839B'
color13='#61869D'
color14='#678CA2'
color15='#c2c4c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
